name = "clawhost-www"
compatibility_date = "2026-04-05"
pages_build_output_dir = "./dist"

[build.environment]
VITE_API_URL = "https://api.clawhost.cloud"
VITE_FIREBASE_API_KEY = "AIzaSyDsBtUiX7c7SLKAR1mmH0SZrDoqbnJDwL8"
VITE_FIREBASE_AUTH_DOMAIN = "clawhost.cloud"
VITE_FIREBASE_PROJECT_ID = "clawhost-prod"
VITE_FIREBASE_STORAGE_BUCKET = "clawhost-prod.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "413543198584"
VITE_FIREBASE_APP_ID = "1:413543198584:web:6f8e3c230f8dd12e0e628d"