import type { ClawDetailTab } from '@/ts/Types'

import { CLAW_DETAIL_TABS } from '@/lib/constants'

const AWAITING_PAYMENT_DISABLED_TABS: ClawDetailTab[] = [
    CLAW_DETAIL_TABS.PREVIEW,
    CLAW_DETAIL_TABS.VERSIONS,
    CLAW_DETAIL_TABS.FILES,
    CLAW_DETAIL_TABS.LOGS,
    CLAW_DETAIL_TABS.TERMINAL,
    CLAW_DETAIL_TABS.MONITOR,
    CLAW_DETAIL_TABS.VOLUMES,
    CLAW_DETAIL_TABS.SECURITY,
    CLAW_DETAIL_TABS.BILLING,
    CLAW_DETAIL_TABS.SERVER
]

export default AWAITING_PAYMENT_DISABLED_TABS